#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00

# Make output directories
mkdir -p out_dir
mkdir -p out_figs

singularity exec docker://brainlife/mne:1.0.2 python3 main.py

cat << EOF > product.json
{
    "brainlife": [
       { 
           "type": "image/png", 
	       "name": "Scalp distribution",
           "base64": "$(base64 -w 0 out_figs/eog_projectors.png)"
       },
       {
           "type": "image/png",
	       "name": "Magnetometers",
           "base64": "$(base64 -w 0 out_figs/meg.png)"
       },
       {
           "type": "image/png",
	       "name": "Gradiometers",
           "base64": "$(base64 -w 0 out_figs/grad.png)"
       },

       {
           "type": "image/png",
	       "name": "EEG",
           "base64": "$(base64 -w 0 out_figs/eeg.png)"
       },
       {
           "type": "image/png",
	       "name": "Joint plot",
           "base64": "$(base64 -w 0 out_figs/joint-plot.png)"
       }
]
}
EOF


